### ISSUE TITLE
Problem within tabs

### ISSUE THREAD

**Issue by tmconnect** [evu/acf-focal_point#1]
Thanks for this awesome plugin.

But I have some problems if I'm using the Focal Point field in tabs. If the field is placed in tabs that are not displayed - that is, all except the first tab - the images are not displayed after saving/reloading the page.

I think the size of the canvas element of the Focal Point field could not be calculated, because the tab is hidden.

Do you have any idea to solve this?

Thanks

**Comment by jhealey5** [comment]
Completely forgot about tabs!

Should be fixed now mate.

Thanks!

**Comment by tmconnect** [comment]
Works perfect - Thanks
