### ISSUE TITLE
Delete icon not show correct

### ISSUE THREAD

**Issue by tmconnect** [evu/acf-focal_point#2]
I'm using ACF V 5.3.3.2 and the class for the delete icon span should not be

`acf-button-delete acf-icon acc-icon-cancel dark`

but

`acf-button-delete acf-icon acf-icon -cancel dark`

Thanks

**Comment by jhealey5** [comment]
ACF must of changed classes with latest update, or remove the space at least :)

Both on now.

Cheers.

**Comment by tmconnect** [comment]
Great - Thanks
