### ISSUE TITLE
Canvas size within columns

### ISSUE THREAD

**Issue by tmconnect** [evu/acf-focal_point#3]
This is no issue - it's more a help call.

Using Focal Point with my "[ACF-Column-Field](https://github.com/tmconnect/ACF-Column-Field)" makes the images very small.

Did you get any idea how I can solve this within my plugin?

Thanks

**Comment by jhealey5** [comment]
Hi mate, just did a little update that should fix the problem. Let me know how it goes for you.

**Comment by tmconnect** [comment]
Thanks, works perfect
