### ISSUE TITLE
No focus box?

### ISSUE THREAD

**Issue by TwoPaperdolls** [evu/acf-focal_point#6]
First off, thanks for taking a crack at this - it's an addon that I would love to use in a lot of projects!

I noticed someone raised a similar issue over on the WP forum about this, but didn't see an answer.  I've installed and activated the plugin, added it as a field and uploaded an image, but I'm not seeing the tool for selecting a focus point anywhere.  I've tried various configuration of object and tag, image and return sizes the same, etc, but not seeing where I actually select the focal point anywhere.

Am I missing something?

**Comment by jhealey5** [comment]
Hi there. Hmm, I'm not sure, unless there's something in a WP update that broke it but has been fine for me. I'll try and get a fresh install set up and see if there's any problems. 

Have you tried disabling all other plugins (other than acf ofc) to see if anything is conflicting? And/or using one of the default Wordpress themes? (in case something in the theme is conflicting).

Do you get any console errors?

And just to cover all mishaps, there are no "controls" you just click and drag a box over the image.

Didn't notice the WP forum either, thanks for the heads up.

**Comment by TwoPaperdolls** [comment]
Thanks for getting back so quickly, evu.

Tried Twentyfifteen theme and the only active plugins are ACF and Focal Point.  No console errors.  Dragging doesn't work at any point - when is the dragging supposed to happen?  In the edit lightbox or the preview image?

Does the FP field have the same look and css classes as the regular ACF img upload field?  From everything I can see in the inspector, it's not displaying the FP field - just the regular ACF img field.

**Comment by TwoPaperdolls** [comment]
Wow, I'm so sorry - total brainfart on my end - plugin is working perfectly and I was mixing my FC field with one farther up the page.
